[project]
name = "dio-bank"
version = "0.1.0"
description = ""
authors = [
    {name = "AlienneSilva",email = "88863077+AlienneSilva@users.noreply.github.com"}
]
requires-python = ">=3.14,<4.0"
dependencies = [
    "flask (>=3.1.3,<4.0.0)",
    "flask-sqlalchemy",
    "psycopg[pool] (>=3.3.6,<4.0.0)",
    "flask-migrate",
    "flask-jwt-extended (>=4.7.4,<5.0.0)",
    "markupsafe (>=3.0.3,<4.0.0)",
    "gunicorn",
    "flask-bcrypt",
    "flask-marshmallow",
    "marshmallow-sqlalchemy",
    "apispec-webframeworks",
    "sqlalchemy[asyncio] (>=2.0.54,<3.0.0)",
    "aiosqlite (>=0.22.1,<0.23.0)",
    "asyncpg (>=0.31.0,<0.32.0)",
    "pydantic-settings (>=2.15.0,<3.0.0)",
    "pydantic[email] (>=2.13.5,<3.0.0)",
    "pyjwt[crypto] (>=2.15.0,<3.0.0)",
    "bcrypt (>=5.0.0,<6.0.0)"
]

[tool.pytest]
addopts = ["-vvv"]
testpaths = ["tests"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest",
    "pytest-mock",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
